export const NICHES = [
  { label: "Dentist", value: "healthcare.dentist" },
  { label: "Restaurant", value: "catering.restaurant" },
  { label: "Lawyer", value: "service.financial,service.financial.lawyer,office" },
  { label: "Plumber", value: "service.construction,service.construction.plumber" },
  { label: "Electrician", value: "service.construction,service.construction.electrician" },
  { label: "Gym", value: "leisure.sport,leisure.sport.fitness" },
  { label: "Auto Repair", value: "service.vehicle,service.vehicle.repair" },
  { label: "Real Estate", value: "service.real_estate" },
  { label: "Accountant", value: "service.financial,service.financial.accountant" },
  { label: "Veterinarian", value: "healthcare.veterinary" }
];

export const CITY_STATE_MAP: Record<string, string> = {
  "New York": "NY",
  "Los Angeles": "CA",
  "Chicago": "IL",
  "Houston": "TX",
  "Phoenix": "AZ",
  "Philadelphia": "PA",
  "San Antonio": "TX",
  "San Diego": "CA",
  "Dallas": "TX",
  "San Jose": "CA",
  "Austin": "TX",
  "Jacksonville": "FL",
  "Fort Worth": "TX",
  "Columbus": "OH",
  "Charlotte": "NC",
  "San Francisco": "CA",
  "Indianapolis": "IN",
  "Seattle": "WA",
  "Denver": "CO",
  "Washington": "DC",
  "Boston": "MA",
  "El Paso": "TX",
  "Nashville": "TN",
  "Detroit": "MI",
  "Oklahoma City": "OK",
  "Portland": "OR",
  "Las Vegas": "NV",
  "Memphis": "TN",
  "Louisville": "KY",
  "Baltimore": "MD",
  "Milwaukee": "WI",
  "Albuquerque": "NM",
  "Tucson": "AZ",
  "Fresno": "CA",
  "Sacramento": "CA",
  "Mesa": "AZ",
  "Kansas City": "MO",
  "Atlanta": "GA",
  "Long Beach": "CA",
  "Omaha": "NE",
  "Raleigh": "NC",
  "Colorado Springs": "CO",
  "Miami": "FL",
  "Virginia Beach": "VA",
  "Oakland": "CA",
  "Minneapolis": "MN",
  "Tulsa": "OK",
  "Arlington": "TX",
  "New Orleans": "LA",
  "Wichita": "KS",
  "Bakersfield": "CA",
  "Tampa": "FL",
  "Aurora": "CO",
  "Honolulu": "HI",
  "Anaheim": "CA",
  "Santa Ana": "CA",
  "Corpus Christi": "TX",
  "Riverside": "CA",
  "Lexington": "KY",
  "St. Louis": "MO",
  "Stockton": "CA",
  "Henderson": "NV",
  "Pittsburgh": "PA",
  "Saint Paul": "MN",
  "Cincinnati": "OH",
  "Anchorage": "AK",
  "Greensboro": "NC",
  "Plano": "TX",
  "Newark": "NJ",
  "Lincoln": "NE",
  "Orlando": "FL",
  "Irvine": "CA",
  "Toledo": "OH",
  "Jersey City": "NJ",
  "Chula Vista": "CA",
  "Durham": "NC",
  "Fort Wayne": "IN",
  "St. Petersburg": "FL",
  "Laredo": "TX",
  "Madison": "WI",
  "Chandler": "AZ",
  "Buffalo": "NY",
  "Lubbock": "TX",
  "Scottsdale": "AZ",
  "Reno": "NV",
  "Glendale": "AZ",
  "Gilbert": "AZ",
  "Winston-Salem": "NC",
  "North Las Vegas": "NV",
  "Norfolk": "VA",
  "Chesapeake": "VA",
  "Garland": "TX",
  "Irving": "TX",
  "Hialeah": "FL",
  "Fremont": "CA",
  "Boise": "ID",
  "Richmond": "VA",
  "Baton Rouge": "LA",
  "Spokane": "WA"
};

export const CITIES = Object.keys(CITY_STATE_MAP).sort();
